import React from 'react'
import { useNavigate } from 'react-router-dom'
import ItemForm from '../components/ItemForm'
import { createItem } from '../services/api'


export default function CreateItem(){
const navigate = useNavigate()


const handleSubmit = async (payload) => {
try{
// backend might expect fields like itemId generated by server
await createItem(payload)
alert('เพิ่มสินค้าสำเร็จ')
navigate('/')
}catch(e){
console.error(e)
alert('ไม่สามารถเพิ่มสินค้าได้')
}
}


return (
<div className="container mt-6">
<h1 className="text-2xl font-bold mb-4">เพิ่มสินค้า</h1>
<ItemForm onSubmit={handleSubmit} />
</div>
)
}